name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    env:
      # A dummy key for the XLSX cache. Increment this when you want this Action to
      # ignore cache and re-download and convert demo files
      DUMMY_XLSX_CACHE_KEY: 0

    steps:
      - uses: actions/checkout@v3
        with:
          path: times-excel-reader

      - name: Install packages
        working-directory: times-excel-reader
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check code formatting
        working-directory: times-excel-reader
        run: |
          pre-commit install
          pre-commit run --all-files

      # ---------- ETSAP Demo models

      - uses: actions/checkout@v3
        with:
          repository: olejandro/demos-dd
          path: benchmarks/dd

      - name: Cache demo xlsx files
        uses: actions/cache@v3
        id: cache-xlsx
        with:
          path: benchmarks/xlsx
          key: ${{ env.DUMMY_XLSX_CACHE_KEY }}

      - name: Download demo files and convert to xlsx
        if: steps.cache-xlsx.outputs.cache-hit != 'true'
        run: |
          wget -nv https://iea-etsap.org/demo-models/VEDA-TIMES%20Demo%20Models.zip
          unzip *.zip
          mv "./VEDA-TIMES Demo Models/ETSAP_DemoS_VFE" benchmarks/xlsx
          sudo apt install libreoffice-calc default-jre libreoffice-java-common
          find benchmarks/xlsx -name "*.xls" -type f -printf "soffice --convert-to xlsx --outdir '%h' '%p'\n" | bash

      # Upload the converted xlsx files as an artifact so that we can download it
      # and reproduce any CI failures locally
      - name: Upload xlsx files as artifact
        uses: actions/upload-artifact@v3
        if: steps.cache-xlsx.outputs.cache-hit != 'true'
        with:
          name: demos-xlsx
          path: benchmarks/xlsx

      # ---------- TIMES Ireland Model

      # We add this model as the directory `ireland` under `benchmarks/{xlsx,dd}/`
      # so that the run_benchmarks.py script runs this model too
      - uses: actions/checkout@v3
        with:
          repository: samwebster/times-ireland-model
          path: benchmarks/xlsx/Ireland

      - uses: actions/checkout@v3
        with:
          repository: MaREI-EPMG/times-ireland-model_gams
          path: benchmarks/dd/Ireland

      - name: Run tool on all benchmarks
        working-directory: times-excel-reader
        run: python utils/run_demos.py ../benchmarks
