name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  demos-test:
    runs-on: ubuntu-latest

    env:
      # A dummy key for the XLSX cache. Increment this when you want this Action to
      # ignore cache and re-download and convert demo files
      DUMMY_XLSX_CACHE_KEY: 0

    steps:
      - uses: actions/checkout@v3
        with:
          path: times-excel-reader

      - name: Install packages
        working-directory: times-excel-reader
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check code formatting
        working-directory: times-excel-reader
        run: |
          pre-commit install
          pre-commit run --all-files


      # TIMS

      - uses: actions/checkout@v3
        with:
          repository: samwebster/times-ireland-model
          path: times-ireland-model

      - uses: actions/checkout@v3
        with:
          repository: MaREI-EPMG/times-ireland-model_gams
          path: times-ireland-model_gams

      - name: Convert ground truth DD to CSV
        working-directory: times-excel-reader
        run: |
          python utils/dd_to_csv.py ../times-ireland-model_gams/model ground_truth

      - name: Run tool on TIMS
        working-directory: times-excel-reader
        run: |
          python times_excel_reader.py ../times-ireland-model


      # Demos

      - uses: actions/checkout@v3
        with:
          repository: olejandro/demos-dd
          path: times-excel-reader/demos-dd

      - name: Cache demo xlsx files
        uses: actions/cache@v3
        id: cache-xlsx
        with:
          path: times-excel-reader/demos-xlsx
          key: ${{ env.DUMMY_XLSX_CACHE_KEY }}

      - name: Download demo files and convert to xlsx
        if: steps.cache-xlsx.outputs.cache-hit != 'true'
        run: |
          wget -nv https://iea-etsap.org/demo-models/VEDA-TIMES%20Demo%20Models.zip
          unzip *.zip
          mv "./VEDA-TIMES Demo Models/ETSAP_DemoS_VFE" times-excel-reader/demos-xlsx
          sudo apt install libreoffice-calc default-jre libreoffice-java-common
          find times-excel-reader/demos-xlsx -name "*.xls" -type f -printf "soffice --convert-to xlsx --outdir '%h' '%p'\n" | bash

      # Upload the converted xlsx files as an artifact so that we can download it
      # and reproduce any CI failures locally
      - name: Upload xlsx files as artifact
        uses: actions/upload-artifact@v3
        if: steps.cache-xlsx.outputs.cache-hit != 'true'
        with:
          name: demos-xlsx
          path: times-excel-reader/demos-xlsx

      - name: Run tool on demos
        working-directory: times-excel-reader
        run: |
          python utils/run_demos.py
